# Generated by Django 5.1 on 2024-08-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='form_model',
        ),
    ]
