# Generated by Django 5.1 on 2024-08-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_form_form_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_model',
            old_name='confirm',
            new_name='reg_number',
        ),
        migrations.RenameField(
            model_name='form_model',
            old_name='password',
            new_name='roll_number',
        ),
    ]
