# Generated by Django 5.1 on 2024-08-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_confirm_form_model_reg_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_model',
            old_name='reg_number',
            new_name='regnumber',
        ),
        migrations.RenameField(
            model_name='form_model',
            old_name='roll_number',
            new_name='rollnumber',
        ),
        migrations.AlterField(
            model_name='form_model',
            name='phone',
            field=models.CharField(max_length=150),
        ),
    ]
