# Generated by Django 5.1 on 2024-08-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_reg_number_form_model_regnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_model',
            name='full_name',
        ),
    ]
