# Generated by Django 5.1 on 2024-08-29 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Birth_Date', models.DateField()),
                ('Blood_Group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('Address', models.CharField(max_length=150)),
                ('Phone', models.CharField(max_length=13)),
                ('Nationality', models.CharField(max_length=30)),
                ('Religion', models.CharField(max_length=50)),
                ('Biodata', models.TextField()),
                ('Profession', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=50)),
                ('Image', models.ImageField(default='default.jpg', upload_to='login/images')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
