# Generated by Django 5.1 on 2024-08-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_userprofile_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Profession',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor')], max_length=50),
        ),
    ]
